### ISSUE TITLE
Pinned Messages/Discussions

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/eos#14]
This is a terrible way to use issues, but because Slack will lose messages...

From Kadesh:

> Regarding eos - it's not complete yet. No projected stuff at all, no fleet stuff at all. Local calculations (within scope of a fit) are lacking:
> - Booster support (side-effect handling)
> - Custom effects support (i saw just AAR effect which has unusual attribute layout, from what i've heard grapplers might be using custom effect too, although these are not very useful in fit-local calcs)
> - Various aggregated attribs - tank, capsim integration etc. This one is easy to implement tho (the only one complex question here might be - do we want to run capsim in different thread or not)
> 
> Pyfa skeleton - far from being ready. Last time i worked on it i realized that thing is getting complex and needs tests for better maintenance for further development, and put it on hold to solve some questions related to testing (eg how to handle database in tests). Then AT13 happened.
> Not all eos objects have corresponding pyfa counterpart, although i consider concept as proven. The only unclear question is mapping between pyfa and eos modules (i want pyfa to have just Module, which will correspond to modulehigh/modmed/modlow in eos, so some automation for picking proper type should be implemented in pyfa skeleton)
> 
> As blitzmann said, eos was designed as number cracker, it has zero understanding of stuff like module names, databases etc. It's for the case if people want to use it for simpler needs (eg calculate killboard fit stats, or build some autoanalysis tools like i wrote for AT purposes).
> 
> Roles of eos:
> - Calculate attrs of separate items
> - Calculate aggregated stats (fit dps, fit cap balance, fleet total mass etc)
> - Fit validation
> 
> Roles of skeleton (pyfa-specific stuff):
> - Integrating eos with other stuff below
> - eve database handling
> - Pyfa (persistence) database handling
> - adjusting API for ease of use in pyfa
> - Undo/redo support
> - Adding some layers missing in eos but needed for pyfa (item names, attribute units, ship races etc)
>

**Comment by DarkFenX** [comment]
Gonna close it. This text was placed there just for archive reasons anyway.
