### ISSUE TITLE
Flake8 validation

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/eos#30]
Currently invoked command:
`flake8 --exclude=.svn,CVS,.bzr,.hg,.git,__pycache__,venv,tests,.tox,build,dist --max-line-length=120`

1) Line length - 119 or 120 characters? I've always used 119 (coming from 79 in pep8)
2) Should ignore F403 (use of starred import) and F405 (possibly undefined name, or used from starred import) events
3) Should not fire an event F401 (imported but not actually used) for `__init__.py` files (or if it's not possible, ignore such files altogether)

Possibly:
4) Turn off E402 (module level import not on top of the file). It contradicts to PEP8 in this case:
> Module level "dunders" (i.e. names with two leading and two trailing underscores) such as __all__ , __author__ , __version__ , etc. should be placed after the module docstring but before any import statements except from __future__ imports. Python mandates that future-imports must appear in the module before any other code except docstrings.

**Comment by Regner** [comment]
1. 119 works for me. I for some reason always thought it was 80 and just increased by 50%.
2. Sounds good
3. Not sure of the best way to handle this. Both those routes bother me a bit. I think I would be more happy with ignoring __init__.py files than ignoring F401.
4. I could go either way (Adding NOQA or turning off E402). I cannot really see allowing someone to break this rule and flake8 seem to get it wrong for dunders. So ignoring E402 seems OK as code reviews should cover it.

**Comment by DarkFenX** [comment]
3) Yeah i wasn't suggesting to disable F401 for all files, it catches many oversights. I agree disabling `__init__.py` is almost perfect. The only errors flake8 caught in them was just extra blank line.
4) Let's disable it altogether.

**Comment by DarkFenX** [comment]
https://github.com/pyfa-org/eos/commit/7ab262d17bb4070684b36b81604f6dfe7d65fe54
