### ISSUE TITLE
T3D modes

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/eos#8]
T3D modes do not seem to exist.

This is just a module in game.

```
  "34564": {
    "descriptionID": 305011, 
    "typeID": 34564, 
    "capacity": 0.0, 
    "description": "33.3% bonus to all shield and armor resistances\r\n66.6% reduction in MicroWarpdrive signature radius penalty", 
    "raceID": 2, 
    "typeNameID": 305010, 
    "iconID": 1042, 
    "published": false, 
    "volume": 5, 
    "typeName": "Svipul Defense Mode", 
    "radius": 50, 
    "basePrice": 0.0, 
    "mass": 100, 
    "groupID": 1306, 
    "portionSize": 1
  }, 
  "34566": {
    "descriptionID": 305014, 
    "typeID": 34566, 
    "capacity": 0.0, 
    "description": "66.6% bonus to maximum velocity\r\n33.3% bonus to ship inertia modifier", 
    "raceID": 2, 
    "typeNameID": 305013, 
    "iconID": 1042, 
    "published": false, 
    "volume": 5.0, 
    "typeName": "Svipul Propulsion Mode", 
    "radius": 50.0, 
    "basePrice": 0.0, 
    "mass": 100.0, 
    "groupID": 1306, 
    "portionSize": 1
  }, 
```

That has effects:

```
  {
    "typeID": 34566, 
    "effectID": 6016, 
    "isDefault": false
  }, 
```

```
  {
    "npcUsageChanceAttributeID": null, 
    "displayNameID": null, 
    "npcActivationChanceAttributeID": null, 
    "iconID": 0, 
    "propulsionChance": false, 
    "effectCategory": 0, 
    "fittingUsageChanceAttributeID": null, 
    "guid": "", 
    "resistanceID": null, 
    "isOffensive": false, 
    "durationAttributeID": null, 
    "rangeAttributeID": null, 
    "dataID": 94699582, 
    "sfxName": null, 
    "description": null, 
    "disallowAutoRepeat": false, 
    "effectName": "modeAgilityPostDiv", 
    "modifierInfo": "- domain: shipID\r\n  func: ItemModifier\r\n  modifiedAttributeID: 70\r\n  modifyingAttributeID: 2002\r\n  operator: 5", 
    "displayName": "", 
    "dischargeAttributeID": null, 
    "falloffAttributeID": null, 
    "descriptionID": null, 
    "isAssistance": false, 
    "isWarpSafe": false, 
    "electronicChance": false, 
    "rangeChance": false, 
    "trackingSpeedAttributeID": null, 
    "effectID": 6016, 
    "postExpression": 2251, 
    "published": false, 
    "preExpression": 2250, 
    "distribution": null
  }, 
```

So for T3Ds, what we _could_ do is simply add them to the fitting engine.

```
fit.t3dmode.equip(T3DMode(34564, state=State.active))   # Svipul Defensive Mode
```

Assuming that Eos isn't filtering out these modules (with it's extremely aggressive filtering), everything _should_ be in place to pick it up.

Eos should only allow 1 T3D mode and error if more than one is provided.

Alternatively, if Eos is caching fitting data (not sure if it is or not), then we can pass all 3 and only have one active at a time.

**Comment by blitzmann** [comment]
I think the t3 dessy modes / stances do exist in EOS:

https://github.com/pyfa-org/eos/blob/master/eos/fit/holder/item/stance.py

I distinctly remember that these are a thing. try `fit.stance = Stance(:typeID:)`

**Comment by blitzmann** [comment]
Also, I completely forgot that Kadesh already start working on the next version of pyfa where he started tying EOS in with pyfa and user data models. 

See this test file: https://github.com/DarkFenX/pyfa-experimental/blob/master/service/data/pyfa_data/stance.py

I'll be making an issue on pyfa-ng repo on how we can potentially utilize this codebase going forward.

**Comment by Ebag333** [comment]
Yeah, I see that `fit.stance` exists, but it doesn't seem to do anything (which looking at the file, makes sense...).

**Comment by blitzmann** [comment]
I believe stance is the proper name for it given by ccp (internal, anyway). Check the tests and see how it's used, last I remember it worked fine, but might need to be tweaked now?

>These "modes" are literally just modules as well, so I wonder if we aren't just over complicating things.

They are special modules, like subsystems, so they need to have their own class and way of doing things. It works more or less the same way in the current pyfa implementation, not sure why you think it's complicated...

**Comment by Ebag333** [comment]
>I believe stance is the proper name for it given by ccp (internal, anyway).

This makes sense.  It's not used anywhere else by CCP, but why would they ever be consistent on naming?

>Check the tests and see how it's used, last I remember it worked fine, but might need to be tweaked now?

I'll look at the tests, but looking at the stances file and trying to dot complete it, it doesn't look good...
https://puu.sh/rHxDN/7b61da6a1c.gif

>They are special modules, like subsystems, so they need to have their own class and way of doing things. It works more or less the same way in the current pyfa implementation, not sure why you think it's complicated...

If you didn't notice, even before you pointed out that stances existed I had suggested we give them their own class. :)

>not sure why you think it's complicated...

That comment is more in regard toward a comment Kadesh made about hard coding some information as to which modules are valid for stances and which aren't.  As far as I'm aware, there's nothing that explicitly flags these as being stance modes, other than they have some `modeXXXXXXXX` fields.

The question then becomes where to do the validation.  _Should_ Eos care if you pass in a non-valid stance module as a stance?  Or a Jackdaw stance on a Hecate?  Since current Pyfa lets you do lots of non-valid things (hello dread guns on a frigate) maybe not.  (Plus we also have the option of having our UI do that validation if we want it.)

Now doing validation such as only allowing 1 stance to be active at a time makes a lot of sense for the fitting engine.  I just hate hard coding things as it means more work down the road if/when CCP adds/moves/deletes/modifies things.

(Speaking of current Pyfa, it would be nice to be able to right click and show info on stance modules, so you could see the effect names and stats.  But that's another topic.)

**Comment by blitzmann** [comment]
> That comment is more in regard toward a comment Kadesh made about hard coding some information as to which modules are valid for stances and which aren't. As far as I'm aware, there's nothing that explicitly flags these as being stance modes, other than they have some modeXXXXXXXX fields.

Current pyfa doesn't hardcode valid stances IIRC. Although I think it might use the item name to determine which is valid and which isn't, which isn't going to work for EOS. since it doesn't have any notition of names.

>The question then becomes where to do the validation. Should Eos care if you pass in a non-valid stance module as a stance?

Yes it should. EOS already does a bunch of validation, I don't see why we would want it to purposefully accept a non valid stance. We may have to create a new data store within EOS cache that maps the stance item to their respective ships. This is something that @DarkFenX should comment on as I still have very little idea on how EOS internals work. If it can't be done with EOS, then we would ahve to do custom validation of it before we send the fit off to EOS to be calculated.

> hello dread guns on a frigate

wtf no way... if this is true we should fix it.

>  I just hate hard coding things as it means more work down the road if/when CCP adds/moves/deletes/modifies things.

Agreed

**Comment by Ebag333** [comment]
>Current pyfa doesn't hardcode valid stances IIRC. Although I think it might use the item name to determine which is valid and which isn't, which isn't going to work for EOS. since it doesn't have any notition of names.

We could have a list of valid item IDs though, and those are less likely to change than names.

>Yes it should. EOS already does a bunch of validation, I don't see why we would want it to purposefully accept a non valid stance. We may have to create a new data store within EOS cache that maps the stance item to their respective ships.

And if you look at the way that Eos tries to validate capital modules on non-capital ships, it's a _huge_ problem.

This is a larger discussion item, I think, but what it boils down to is this: we are taking an arbitrary data set, and expecting Eos to make rule based logic decisions to pass/fail that data set.  And not only is the data set arbitrary, but it can be modified or added to (or reduced/removed, but that's less likely to happen).

There are basically three ways to handle this.
1. Write really complex rules that may or may not work, and spend hours pulling you hair out.
2. Hard code it in some fashion (libraries and lists).  This requires lots of maintenance and isn't dynamic at all.
3. Accept that there's not a good way to do this and don't do it. (Handle it elsewhere if possible.)

I won't lie and pretend that option 3 fixes our problems, in our particular case it just shoves it off to the UI and/or the user.  But I'd rather handle that particular problem in the UI than in the fitting engine.

There are valid cases for passing in illegal fits to the fitting engine, mostly revolving around this that are technically illegal but we don't want to stop users from doing (like being 1% over on PG).  How do you differentiate between an illegal fit that's 1% over on PG, and an illegal fit that uses a dread module on a frigate?  What about an illegal fit that uses a BS mod on a cruiser? (More on that later).

Eos _should_ do as much validation as it can, but it _shouldn't_ do validation based on arbitrary data (or rather, should do it as little as possible).  In the case of stances, they are simply a module with nothing identifying them as being a stance, or being tied to a particular ship.

>wtf no way... if this is true we should fix it.

You know, the gun DPS on this Velator is pretty terrible, but the drone DPS and tank is quite nice.  I might need a genolution set to make it all fit.....
https://puu.sh/rI28t/5bf874886b.png

We can go over all the various things that are wrong with this fit, but it boils down to one particular problem, how do we tell the difference between an illegal fit that's okay and an illegal fit that's not?

This is where the `capital_item.py` validation in Eos falls down, it assumes that anything over 500 volume _must_ be a capital mod.  Except that lots of stuff _isn't_.  And there's no reason that a capital mod can't be smaller than 500.  It's using option number 1, and has the potential to fail in both directions.

Sure, we can hard code a list of capital modules (option 2), which is relatively easy when they're in their own XL market group. But how about stuff like the Networked Sensor Array which is just a special sensor booster?  Also, not only is it a capital module, but it's a _carrier only_ module.  Yet there's _nothing_ on the item that would indicate either of these facts, it's simply known (easy for a person to do, hard for a computer to do).

Here's what I think we should do.

In Eos:
1. Validate everything we can that we have data from from the JSON.
2. Do not validate against hard coded arbitrary lists.

In Pyfa GUI:
1. Create our hard coded arbitrary lists.
2. If a user attempts to do something that fails, pop up a warning informing them that this is not a vaild fitting choice.
3. Allow the user to continue to do so if they select yes.

I believe that this is our best solution because it keeps Eos focused on the hard data, and away from the time consuming hand curated lists that may or may not be accurate.

In the GUI, we warn the user that they are trying to do something they shouldn't, but allow them to do so anyway.  Maybe because they're simply curious. Maybe because CCP made a change we haven't implemented yet.  Maybe they know what they're doing is not a legal fit but they want to do it anyway to test something or prove a point in an online debate with other spaceship nerds.



Okay, all of that to say, here's my recommendation for this particular use case.

1. Ideally we don't validate the module passed as the stance at all, since we have no hard data to validate against (we leave it up to the UI and/or user to handle that).
2. Alternatively, we validate two things: that the module has attributes that start with `mode`, and the module's name has the ship name in it (`Svipul Defensive Mode` matches `Svipul` but not `Jackdaw`).  This is fairly risky for a number of issues, but it would work today.
3. Last (and my least favorite), create a hand curated list based off the item ID.

**Comment by blitzmann** [comment]
> There are valid cases for passing in illegal fits to the fitting engine, mostly revolving around this that are technically illegal but we don't want to stop users from doing (like being 1% over on PG). 

We're not talking about being over on resources though. We are talking about literally fitting a module that doesn't mesh with the ship. It's not made for that ship and shouldn't ever be used with the ship. To me, it's akin to allowing subsystems on a Rifter. lolwut?

> How do you differentiate between an illegal fit that's 1% over on PG, and an illegal fit that uses a dread module on a frigate? What about an illegal fit that uses a BS mod on a cruiser?

I differentiate it by if the game actually allows it. I know I said we should fit current pyfa's issue of having a dread gun on a frigate, but I thought it actually had a mechanism in place to not allow it. i don't remember how it works in game, and I'm not going to break my winning streak by logging in, but IIRC it's technically possible, even in game. There are absolutely no mechanisms in place for not allowing it, the only restriction is the resources (which implicitly disallow it rather than explicitly).  You can have BS sized modules on lower class ships as long as you have the fitting requirements for it.

For stances, though, it is literally impossible to have a minmatar stance on the amarr t3d. That's my criteria.

> But how about stuff like the Networked Sensor Array which is just a special sensor booster? Also, not only is it a capital module, but it's a carrier only module. Yet there's nothing on the item that would indicate either of these facts, 

Current pyfa doesn't allow it to be fit to anything other than a carrier. It has a "Can be fitted to" attribute. Or are you talking about EOS allowing it?

I think we are getting too in depth with this at the moment. This isn't something that really needs to be solved for immediately. My initial opinion is that if it's not explicitly allowed in game, then it's not allowed in EOS, period. However, I do see the possible benefit to having a dialog say "yo, this shit isn't going to work" and allowing it anyway. But when it comes to EOS, I'd much rather have @DarkFenX comment on it.

**Comment by Ebag333** [comment]
>We're not talking about being over on resources though. We are talking about literally fitting a module that doesn't mesh with the ship. It's not made for that ship and shouldn't ever be used with the ship. To me, it's akin to allowing subsystems on a Rifter. lolwut?

Apples and oranges though.

Number of subsystem slots on a rifter is non-existent, while a Loki has `maxSubSystems` set to `5`.

>I differentiate it by if the game actually allows it.

Even the game limits some of that stuff to the front end, and some to the back end. :)

>i don't remember how it works in game

It's hard coded somewhere (99% sure of that).

>I think we are getting too in depth with this at the moment. This isn't something that really needs to be solved for immediately.

I don't think we are, but it's a more general issue that extends beyond stances.

Basically the question is, we _will_ need to have a hard coded curated list somewhere out there, and where do we handle it?  Personally I'm of the view of keeping Eos to be as data driven as possible (via the JSON and input data) and handle any hard coded lists outside of that (either in the Framework/Skeleton, or in the UI itself).

**Comment by DarkFenX** [comment]
First, name. CCP uses stance to refer to t3d mode. I have no strong opinion on that, but i prefer stance as it is short, unique and accurately depicts how ship changes when you change mode. Tactical may refer to anything with word tactical, tactical_mode is a bit long. We can change it but i'd prefer to keep it as is.

> Should Eos care if you pass in a non-valid stance module as a stance?
Will comment it in #18

> Now doing validation such as only allowing 1 stance to be active at a time makes a lot of sense for the fitting engine.
Eos is already doing that.

1) Each time you assign new fit.stance, old one gets removed.
2) You cannot put stance to any other endpoint, endpoints are doing class check when you put items into them. This is example of single-item endpoint doing this, it's the same for multi-item containers: https://github.com/pyfa-org/eos/blob/master/eos/fit/holder/container/single_onfit.py#L48
3) There're some checks which verify if typeID stored within Stance instance is actually stance: https://github.com/pyfa-org/eos/blob/master/eos/fit/restriction_tracker/register/holder_class.py#L69

Conjunction of all three points covers many things related to stances.

> And if you look at the way that Eos tries to validate capital modules on non-capital ships, it's a huge problem.
That's off-topic. Gonna comment it in pull rq #18


Anyway, to the topic. Stances work in Eos:
```
def confessor():

    fit = Fit()
    fit.ship = Ship(34317)  # Confessor
    fit.stance = Stance(34319)  # Def mode

    for skill_id in skills:
        fit.skills.add(Skill(skill_id, level=5))

    print(fit.stats.agility_factor)

    fit.stance = Stance(34323)  # Prop mode

    print(fit.stats.agility_factor)
```
Output is:
$ python3 run.py 
5.053042946282003
3.3686952975213345

Closing issue. If you have anything to add and want to continue discussion, file new issue or continue in slack.

**Comment by DarkFenX** [comment]
Also lol @ dot completion. It's supposed to be assigned directly. See example above. That's how descriptors work.

**Comment by Ebag333** [comment]
```
    fit = Fit()
    fit.ship = Ship(34317)  # Confessor
    fit.stance = Stance(34319)  # Def mode

    for skill_id in skills:
        fit.skills.add(Skill(skill_id, level=5))

    print(fit.stats.agility_factor)

    fit.stance = Stance(34323)  # Prop mode
```

This is not at all how the example is given in the readme.  It's also a very different way of doing things than every other module/rig/sub/skill/etc.

>It's supposed to be assigned directly. See example above. That's how descriptors work.

So according to your example:
`fit.stance = Stance(34323)  # Prop mode`

Yet every other method (that I've seen so far) of passing in a value uses a completely different method of doing so:
```
 fit.skills.add(Skill(skill_id, level=5))
fit.modules.high.equip(ModuleHigh(35924, state=State.active))
fit.subsystems.add(Subsystem(29971))
```
etc

Okay, I _get_ that you can do things many ways in Python, and they're all legit (hello importing modules).  That being said, let me try a few things.

Using this bit of code (which, without knowing the internals and just going off every other bit of code is what I'd expect):
```
fit.ship = Ship(34317)
fit.stance.add(Stance(34323, state=State.active))
```

Returns an error:
`AttributeError: 'NoneType' object has no attribute 'add'`

Okay, using your code, it _does_ process the fit....but as far as I can see the value doesn't change.

It's entirely possible that I'm looking in the wrong place, but none of the values I found associated with attribute type 37 (max velocity) changed.

fit.ship.item.attributes seems to be the dict that holds all the values, is there somewhere else to be looking for the modified value (I know that old Eos has an original and modified value location).

.
So the TL; DR is that I'm not sure why stances are handled different than the rest of the modules (since they are, literally a module), this is just confusing and a higher bar of entry for someone learning how to use Eos.

I'm also not sure that they're applying correctly, but it's entirely possible I've missed the modified value.

**Comment by Ebag333** [comment]
Also, can you not be _quite_ so quick to close these with `lol noob` comments?

**Comment by blitzmann** [comment]
> It's a very different way of doing things than every other module/rig/sub/skill/etc. The only thing that uses that format is ship, and a stance is a module not a ship so......

Yes, they are a module, but only because that's how CCP implemented them to make them work. They aren't actually a module. See WH effects which are implemented as a 'projected module'. That being said, it should also be considered that all other 'modules' are a collection of something. Subsystems are a collection, slot modules are a collection, skills are a collection. Stances, on the other hand, are not a collection, and so they do not need to be `add()`'d so to speak. They are assigned directly. Just like Ship is not a collection. Each fit has one and only one fit, same with stance.

It a different way of expressing it, but it's not an incorrect way. The only change that I can see that might be proposed would be to have it branch off of `fit.ship` instead of `fit`, but it makes logical sense either way so there's no need to change it.

Also, this is how I recommended to use it. From my previous comment:

> `fit.stance = Stance(:typeID:)`

Did you try this and it not work at the time? 

> Okay, using your code, it does process the fit....but as far as I can see the value doesn't change.

I haven't tested it myself, but @DarkFenX posted the snippet that he used and the output. You are not getting the same results? Perhaps post the snippet that you are using which is not working.
