### ISSUE TITLE
T3C Subsystems

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/eos#9]
T3C Subsystems don't seem to exist.

Suggest we do something like:

```
fit.modules.subsystem.equip(ModuleSubsystem(2048))
```

We don't need states for it as you can't online/offline them.

Eos should error if more than 1 subsystem of each type is provided (so 2 propulsion ones) or if any of the 5 types are missing.

**Comment by Ebag333** [comment]
Okay, so I found subsystems, they just weren't where I was expecting them to be.

Proteus Defensive - Augmented Plating
```
fit.subsystems.add(Subsystem(29981))
```

One potential issue is that it seems to allow you to online/offline subsystems.  The game doesn't support that.

https://puu.sh/rARDn/146912cfc9.png

We can simply always pass it to be online if we don't want to mess with it.

**Comment by DarkFenX** [comment]
Any item in eos has state. It's the way eos and EVE work and it's not going to change. All the effects turning on and off is based on states.

Not all of the items expose ability to change it. In the case of subsystem - it's instantiated with offline state and you cannot change it. For more info check following files:

https://github.com/pyfa-org/eos/blob/master/eos/fit/holder/mixin/state.py#L25
https://github.com/pyfa-org/eos/blob/master/eos/fit/holder/item/subsystem.py

Poke me if you need any additional help or want to change something,
